apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compositor-data
  namespace: tenant-grupo4-egs-deti-ua-pt
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
