apiVersion: v1
kind: Secret
metadata:
  name: voltguard-secrets
  namespace: tenant-grupo4-egs-deti-ua-pt
stringData:
  # Compositor backend
  COMPOSITOR_KC_SECRET: "change-me-in-production"
  COMPOSITOR_SESSION_SECRET: "change-me-random-32-chars"
  NOTIFICATIONS_AUTH_TOKEN: "your_secure_auth_token"
  ANOMALY_APP_TOKEN: "token_do_composer_123"
